quarkus.http.port=3000

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=user
quarkus.datasource.password=user
quarkus.datasource.jdbc.url=jdbc:postgresql://postgres:5432/uzume

quarkus.http.host=0.0.0.0
quarkus.hibernate-orm.schema-management.strategy=update

smallrye.jwt.sign.key.location=/run/secrets/jwt/privateKey.pem

mp.jwt.verify.publickey.location=/run/secrets/jwt/publicKey.pem
mp.jwt.verify.issuer=uzume

quarkus.log.category."io.quarkus.smallrye.jwt".level=DEBUG
quarkus.log.category."io.smallrye.jwt".level=DEBUG